---

# The project Docker compose file for development.

version: '2.0'

services:
  config:
    extends:
      file: docker-compose-lib.yaml
      service: config

  ## print:
  ##   extends:
  ##     file: docker-compose-lib.yaml
  ##     service: print
  ##   volumes_from:
  ##     - config:ro

  mapserver:
    extends:
      file: docker-compose-lib.yaml
      service: mapserver
    volumes_from:
      - config:ro
    volumes:
      - /var/sig:/var/sig:ro

  ## qgisserver:
  ##   extends:
  ##     file: docker-compose-lib.yaml
  ##     service: qgisserver
  ##   volumes_from:
  ##     - config:ro
  ##   environment:
  ##     # Single QGIS project files
  ##     - QGIS_PROJECT_FILE=/etc/qgisserver/project.qgz
  ##     - GEOMAPFISH_OGCSERVER=<OGC server name>
  ##     # Multiple QGIS project files
  ##     - QGIS_PROJECT_FILE=
  ##     - GEOMAPFISH_ACCESSCONTROL_CONFIG=/etc/qgisserver/accesscontrol_config.yaml

  tinyows:
    extends:
      file: docker-compose-lib.yaml
      service: tinyows
    volumes_from:
      - config:ro

  redis:
    extends:
      file: docker-compose-lib.yaml
      service: redis

  tilecloudchain:
    extends:
      file: docker-compose-lib.yaml
      service: tilecloudchain
    volumes_from:
      - config:ro
    volumes:
      - ./__fix/pyramid_logging.py:/opt/c2cwsgiutils/c2cwsgiutils/pyramid_logging.py

  tilegeneration_slave:
    extends:
      file: docker-compose-lib.yaml
      service: tilegeneration_slave
    volumes_from:
      - config:ro
    volumes:
      - ./__fix/__init__.py:/app/tilecloud_chain/__init__.py

  geoportal:
    extends:
      file: docker-compose-lib.yaml
      service: geoportal
    volumes_from:
      - config:ro
    volumes:
      - /var/sig:/var/sig:ro
      - ./__fix/pyramid_logging.py:/opt/c2cwsgiutils/c2cwsgiutils/pyramid_logging.py
      - ./__fix/env.py:/opt/alembic/env.py

  alembic:
    extends:
      file: docker-compose-lib.yaml
      service: alembic
    volumes:
      - ./__fix/env.py:/opt/alembic/env.py

  front:
    extends:
      file: docker-compose-lib.yaml
      service: front
    volumes_from:
      - config:ro

  # Rich image for project development with e.-g. vim, tree, awscli, psql, ...
  tools:
    volumes_from:
      - config:rw
    volumes:
      - .:/src
    extends:
      file: docker-compose-lib.yaml
      service: tools
